### ISSUE TITLE
Won't work with NeoVim 0.9.0

### ISSUE THREAD

**Issue by natewallis** [c-brenn/mix-test.vim#1]
Hi - thanks for the plugin. 

I can't get this working inside NeoVim 0.9.0.

I know VIM and NeoVim aren't completely compatible so I am assuming this plugin is one of those that won't work.  Have you heard of anyone who has got it working?

Thanks...

**Comment by c-brenn** [comment]
Hi there, thanks for your interest in this plugin. It hasn't been actively maintained in years so it's no surprise that it has stopped working 😅 I don't plan on making any contributions to this repo, but if you find it useful then pull requests are welcome ❤️ 

Personally I have been using [vim-test](https://github.com/vim-test/vim-test) for quite some time and would recommend it as an alternative that works very well (and supports many different test runners).

**Comment by natewallis** [comment]
No worries..  didn’t realise it was a little out of date.  Since my
original post I found vim-test (like you suggested) and yes, it works
well….

Thanks for the info
